### ISSUE TITLE
name 's_dist' is not defined

### ISSUE THREAD

**Issue by AsadTanvir** [timothyjamesbecker/transit_alignment#2]
I git-cloned the latest repository. Then created a  **Python 3.6.15** environment with all the required dependencies, and ran the commands below in Windows command prompt one after another :-  

> **python preprocess_network.py --in_path ha_network/ --cpus 4**

> **python search.py --net_dir ha_network/ --demand_path ha_demand/csts_11022020.txt --out_dir transit_result/ --max_trans 2 --buff_time 10.0 --cpus 4**

The preprocess_network.py runs fine and generates network.pickle.gz file in network folder. Then search.py also runs but the output shows this message: **“name 's_dist' is not defined"** (image-1 below). And the generated human-readable tsv output is blank (image-2). There are also no pickle files generated for each trip in the output.
![image](https://user-images.githubusercontent.com/34921760/173477550-9c7394e9-213a-47ee-b01f-9dc2313bdf01.png)

![image](https://user-images.githubusercontent.com/34921760/174826463-59d78723-9932-4f79-a20b-61319333a116.png)

To resolve it do we need to add this ‘s_dist’ parameter somewhere in the **RTS_FULL** and **get_seq_paths** functions? @timothyjamesbecker

**Comment by AsadTanvir** [comment]
@timothyjamesbecker Please have a look at it. It won't take much time to identify the issue I believe.

**Comment by timothyjamesbecker** [comment]
This issue can not be recreated on the development test system.  This exact command line runs and produces a result file that has paths.  Closing for now since this may be a system or environment issue.

**Comment by AsadTanvir** [comment]
@timothyjamesbecker, is it possible to share the versions (ie. python version, other libraries' versions) you are using?
